In [3]:
import scipy.linalg as linalg
import numpy as np

In [5]:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])
A

array([[2, 1, 1],
       [1, 3, 2],
       [1, 0, 0]])

In [9]:
P, L, U = linalg.lu(A)

P


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [11]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [12]:
np.round(L.dot(U))

array([[ 2.,  1.,  1.],
       [ 1.,  3.,  2.],
       [ 1.,  0., -0.]])

In [13]:
print(np.dot(P.T, A))

[[2. 1. 1.]
 [1. 3. 2.]
 [1. 0. 0.]]


In [15]:
np.round(np.dot(L, U))

array([[ 2.,  1.,  1.],
       [ 1.,  3.,  2.],
       [ 1.,  0., -0.]])